[new] Added support for <optgroup> in select field
iconicwp/WordPress-Settings-Framework pull request #59
Opened 2021-08-10 15:03 UTC by mattwatsoncodes

Added support for <optgroup> in the select field if an option is passed through as an array. 

<img width="1441" alt="Screenshot 2021-08-10 at 16 03 14" src="https://user-images.githubusercontent.com/2066205/128891233-2911c586-7708-43e8-99a4-1522000af2f8.png">

2021-08-30 05:58 UTC, pramodjodhani requested changes

2021-08-30 05:58 UTC, pramodjodhani commented on wp-settings-framework.php
> +					echo sprintf( '<optgroup label="%s">', $value );
Maybe we should use esc_attr( $value  ) here?

2021-08-30 05:58 UTC, pramodjodhani commented on wp-settings-framework.php
> +						echo sprintf( '<option value="%s" %s>%s</option>', $group_value, $selected, $group_text );
We could use esc_* functions here too

2021-08-31 11:45 UTC, mattwatsoncodes commented
Sorted @pramodjodhani and escaped a few other parts of that function while I was there too :)

2021-08-31 13:27 UTC, pramodjodhani commented
Hi @mattwatsoncodes,  Yes it looks great. You haven't re-requested the review but consider it approved from my end 🙌

2021-08-31 13:28 UTC, merged