[new] Show and hide tabs and controls with control groups
iconicwp/WordPress-Settings-Framework pull request #64
Opened 2021-09-24 08:55 UTC by mattwatsoncodes

Fixes #61.

**To show and hide tabs:**

```
$settings['tabs'][] = array(
    'id'              => 'styles',
    'title'           => __( 'Styles', 'flux-checkout' ),
    'tabControlGroup' => 'desktop_enabled',
    // 'showIfValue'     => array( true ), // show if will hide the tab unless the value matches.
    'hideIfValue'     => array( true ), // hide will show the tab unless the value matches.
);
```

On your control, be sure to set the same control name:

```
array(
        'id'              => 'desktop_enabled',
        'title'           => __( 'Enable on Desktop', 'flux-checkout' ),
        'subtitle'        => __( 'Enable or disable Flux Checkout on Desktop.', 'flux-checkout' ),
        'type'            => 'toggle',
        'default'         => true,
        'tabControlGroup' => 'desktop_enabled', // Needs to be set to the same tab control. Does not have to match the Id of this control. 
),
```

**To show and hide controls**

```
array(
        'id'               => 'logo_image',
        'title'            => __( 'Header Image', 'flux-checkout' ),
        'subtitle'         => __( 'Select your logo (Recommended size: 200 x 40px).', 'flux-checkout' ),
        'type'             => 'file',
        'showControlGroup' => 'header',
        'showIfValue'      => array( 'image' ),  // show if will hide the control unless the value matches.
        // 'hideIfValue'      => array( 'text' ),  // hide if will show the control unless the value matches.
),
```

You need to set the control that the values are taken from like this:

```
array(
        'id'               => 'branding',
        'title'            => __( 'Header Type', 'flux-checkout' ),
        'subtitle'         => __( 'Select whether to use an image or text for the branding.', 'flux-checkout' ),
        'type'             => 'select',
        'choices'          => array(
	        'text'  => __( 'Text', 'flux-checkout' ),
	        'image' => __( 'Image', 'flux-checkout' ),
        ),
        'default'          => 'text',
        'class'            => 'header-type',
        'showControlGroup' => 'header', // Needs to be set to the same control. Does not have to match the Id of this control. 
),
```

Demo here: https://cln.sh/Wiwuhw

2021-10-05 12:43 UTC, jamesckemp reviewed
I only have 2 concerns:

1. We use underscores, rather than camelcase, for consitency.
2. How does `showControlGroup` know it's the field to use as a value, rather than just another control to show/hide?

2021-10-05 12:47 UTC, mattwatsoncodes commented
@jamesckemp no worries I can solve the case issue fairly quickly. 

With regards to `showControlGroup` knowing it's the field to use as a value, if it does not have `showIfValue` or `hideIfValue` set then it is configured as the parent control.

To be honest, I should probably rename that one to `show_controller` or 'show_control_parent` or something similar.

2021-10-05 15:24 UTC, jamesckemp requested changes
Looking much better, thanks.

We can hide tabs and fields, but can we hide sections as well?

2021-10-05 15:24 UTC, jamesckemp commented on settings/example-settings.php
> +		array(
Should this be inside the fields array?

2021-10-06 09:56 UTC, mattwatsoncodes commented
![CleanShot 2021-10-06 at 10 54 46](https://user-images.githubusercontent.com/2066205/136181515-4f50c757-ba79-4e6c-abbd-71032d8eb29d.gif)

Now with the ability to show and hide sections 👍 @jamesckemp

2021-10-06 12:46 UTC, jamesckemp requested changes

2021-10-06 12:46 UTC, jamesckemp commented on settings/example-settings.php
> +				'show_control_group' => 'control-group', // Needs to be set to the control group.
I'm wondering if we should call these `field_control_group` just to match the format of tab and section?

2021-10-07 08:10 UTC, mattwatsoncodes commented
@jamesckemp syntax changed as requested 👍 back to you.

2021-11-24 09:15 UTC, jamesckemp approved these changes

2021-11-24 09:15 UTC, merged