Add code editor field
iconicwp/WordPress-Settings-Framework pull request #68
Opened 2021-12-09 10:26 UTC by workeffortwaste

Added support for a code editor field using WordPress's CodeMirror editor.

Supplying the 'mimetype' argument when creating the field will let you select the syntax highlighting used for the editor.

```php
array(
  'id'          => 'codeeditor',
  'title'       => 'Code Editor',
  'desc'        => 'This is a description.',
  'placeholder' => 'This is a placeholder.',
  'type'        => 'codeeditor',
  'mimetype'    => 'css',
  'default'     => 'This is default.',
)
```

2022-02-25 19:21 UTC, workeffortwaste commented
Fixed the merge conflicts due to changes to the `example-settings.php` file since the PR was opened.

2022-02-28 12:13 UTC, namespace-dave requested changes
@workeffortwaste couple of comments but otherwise looking good!

2022-02-28 12:13 UTC, namespace-dave commented on wp-settings-framework.php
> +		public function generate_codeeditor_field( $args ) {
@workeffortwaste can we escape all argument parameter outputs here?

2022-02-28 12:13 UTC, namespace-dave commented on wp-settings-framework.php
> +			echo '<textarea name="' . $args['name'] . '" id="' . $args['id'] . '" placeholder="' . $args['placeholder'] . '" rows="5" cols="60" class="' . $args['class'] . '">' . $args['value'] . '</textarea>
@workeffortwaste might be a bit cleaner to use `printf` here?

2022-02-28 12:13 UTC, namespace-dave commented on settings/example-settings.php
> +				'id'          => 'codeeditor',
@workeffortwaste can we not go with `code_editor` here (and elsewhere)?

2022-02-28 13:16 UTC, workeffortwaste commented
All the requested changes should be done, let me know if you're happy with it.

2022-04-06 11:42 UTC, Rahmon approved these changes
LGTM

2022-04-06 11:43 UTC, merged